# -*- coding: utf-8 -*-
"""Roller_Coaster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbyRhOKrOqVN3NiqzJVt8DijVE30JAGf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import datetime as dt
plt.style.use('ggplot')
#pd.set_option('max_columns' , 200)

df = pd.read_csv("/content/coaster_db.csv")

df.shape

df.head(3)

df.tail(3)

df.sample(3)

df.columns

df.dtypes

df.info()

df.describe()

df.describe(include = 'object')

"""# **Data Preparation**"""

df.columns

df = df[['coaster_name',
    #'Length', 'Speed',
    'Location', 'Status',
    #'Opening date',
       'Type',
    'Manufacturer', 'Height restriction', 'Model', 'Height',
       #'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       #'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       #'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       #'Track layout', 'Fastrack available', 'Soft opening date.1',
       #'Closing date',
    #'Opened',
    #'Replaced by', 'Website',
       #'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       #'Single rider line available', 'Restraint Style',
       #'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean',
    #'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph',
    'height_value', 'height_unit',
    'height_ft',
       'Inversions_clean', 'Gforce_clean']].copy()

df.head()

df.drop(columns = ['height_value'] , inplace = True)

df.drop(['height_unit'] , axis = 1 , inplace = True)

df.shape

df.tail()

df.drop(['Type'] , axis = 1 , inplace = True)

df.columns

df = df[['coaster_name', 'Location', 'Status', 'Manufacturer',
       #'Height restriction', 'Model', 'Height',
    'year_introduced', 'latitude',
       'longitude', 'Type_Main', 'opening_date_clean', 'speed_mph',
       'height_ft', 'Inversions_clean', 'Gforce_clean']].copy()

df.shape

df.dtypes

df["opening_date_clean"] = pd.to_datetime(df['opening_date_clean'])

df.sample()

df['year_introduced'] = df['year_introduced'].astype('object')

df.info()

df['year_introduced'] = pd.to_numeric(df['year_introduced'])

df.rename(columns= {'coaster_name' : 'Coaster_Name' ,
                    'year_introduced' : 'Year_Introduced' ,
                    'opening_date_clean' : 'Opening_Date_Clean' ,
                    'speed_mph' : 'Speed_MPH' ,
                    'height_ft' : 'Height_Ft' ,
                    'Inversions_clean' : 'Inversions' ,
                    'Gforce_clean' : 'Gforce'} ,
          inplace = True)

df.head()

df.isna().sum()

df.isnull().sum()

df.duplicated().sum()

df.loc[df.duplicated()]

df.loc[df.duplicated(subset = ['Coaster_Name'])]

df.query("Coaster_Name == 'Crystal Beach Cyclone'")

df[df['Coaster_Name'] == 'Crystal Beach Cyclone']

df.query("Coaster_Name == 'Derby Racer'")

df[df['Coaster_Name'] == 'Derby Racer']

df.columns

df = df.loc[~df.duplicated(subset = ['Coaster_Name' , 'Location' , 'Opening_Date_Clean'])].reset_index(drop = True).copy()

df.shape

"""# **Univariate Analysis**"""

df.head()

df['Year_Introduced'].value_counts()

df['Year_Introduced'].nunique()

df['Year_Introduced'].unique()

plt.figure(figsize = (14 , 5))
ax = df['Year_Introduced'].value_counts().head(10).plot(kind = 'bar' , title = '\nTop Years Coasters Introduced\n')
plt.xticks(rotation = 360)
ax.set_ylabel('\nFrequency\n')
ax.set_xlabel('\nCoasters Names\n')
plt.show()

plt.figure(figsize = (14 , 5))
ax = df['Year_Introduced'].value_counts().head(10).plot(kind = 'barh' , title = '\nTop Years Coasters Introduced\n')
plt.xticks(rotation = 360)
ax.set_xlabel('\nFrequency\n')
ax.set_ylabel('\nCoasters Names\n')
plt.show()

plt.figure(figsize = (14 , 5))
ax = df['Speed_MPH'].plot(kind = 'hist'
                          , bins = 20
                          , title = '\nCoaster Speed Distribution\n')
ax.set_xlabel('\nCoaster Speed\n')
ax.set_ylabel('\nFrequencey\n')
plt.show()

plt.figure(figsize = (14 , 5))
ax = df['Speed_MPH'].plot(kind = 'kde'
                               , title= 'Coaster Speed Distribution')

ax.set_ylabel('\nCoaster\n')
plt.show()

df.head()

plt.figure(figsize = (14 , 5))
df.plot(kind = 'scatter' ,
        x = 'Speed_MPH' ,
        y = 'Height_Ft' ,
        title = '\nCoaster Speed Vs Height\n')

plt.xlabel('\nCoaster Speed\n' , fontsize = 12)
plt.ylabel('\nHeight\n' , fontsize = 12)
plt.grid(True , alpha = 0.5)
plt.show()

plt.figure(figsize = (14 , 5))
sns.scatterplot(data = df ,
                x = 'Speed_MPH' ,
                y = 'Height_Ft'
                )
plt.title('\nCoaster Speed Vs Height Correlation\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nCoaster Speed\n' , fontsize = 12)
plt.ylabel('\nHeight\n' , fontsize = 12)
plt.grid(True , alpha = 0.5)
plt.show()

plt.figure(figsize = (14 , 5))
sns.scatterplot(data = df ,
                x = 'Speed_MPH' ,
                y = 'Height_Ft' ,
                hue = 'Year_Introduced'
                )
plt.title('\nCoaster Speed Vs Height Correlation\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nCoaster Speed\n' , fontsize = 12)
plt.ylabel('\nHeight\n' , fontsize = 12)
plt.grid(True , alpha = 0.5)
plt.show()

sns.pairplot( data = df ,
             vars = ["Year_Introduced" , "Speed_MPH" , "Height_Ft" , "Inversions" , "Gforce"])
# plt.title('\nFeatures Correlations\n' , fontsize = 16 , fontweight = 'bold')
# plt.tight_layout()
plt.show()

sns.pairplot( data = df ,
             vars = ["Year_Introduced" , "Speed_MPH" , "Height_Ft" , "Inversions" , "Gforce"] ,
              hue = 'Type_Main')
# plt.title('\nFeatures Correlations\n' , fontsize = 16 , fontweight = 'bold')
plt.show()

Df_Corr = df[["Year_Introduced" , "Speed_MPH" , "Height_Ft" , "Inversions" , "Gforce"]].dropna().corr()
Df_Corr

plt.figure(figsize = (14 , 5))
sns.heatmap(Df_Corr , annot = True)
plt.title('\nCorrelations\n' , fontsize = 15 , fontweight = 'bold')

df['Location'].value_counts()

df.query("Location != 'Other'").groupby('Location')['Speed_MPH'].agg(['mean'
                                                                      , 'count']).query("count >= 10").sort_values('mean')['mean'].plot(kind = 'barh' ,
                                                                                                                                        figsize = (15 , 5) ,
                                                                                                                                        title = '\nAvg Speeds by Locations\n')
plt.xlabel('\nAverage Coaster Speed\n' , fontsize = 12)
plt.ylabel('\nLocations\n' , fontsize = 12)
plt.show()

